name: clean_teste
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  data_connection_checker_tv: ^0.3.5-nullsafety
  equatable: ^2.0.3
  get: ^4.3.8
  get_storage: ^2.0.3
  http: ^0.13.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  mocktail: ^0.1.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
